services:
  file-chown:
    container_name: file-chown
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    user: "root"
    volumes:
      - "./storage:/home/runner"
    command: "chown -R runner:runner /home/runner"

  comfyui:
    container_name: comfyui
    depends_on:
      file-chown:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/home/runner"
    environment:
      - CLI_ARGS= "--listen"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
